version: "3.7"
services:
  fwui:
    build: ..
      # context: https://github.com/cyr-ius/firewall-ui.git#master
      # dockerfile: Dockerfile
    container_name: fwui-app
    restart: unless-stopped
    privileged: true
    volumes:
      - static_volume:/opt/static
      - database_volume:/opt/database
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /var/run/dbus:/var/run/dbus
      - /var/log/journal:/var/log/journal:ro            
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Paris
      - SALT=0123456789
      - SECRET_KEY=01234567890123456789

  web:
    image: nginx:stable-alpine
    container_name: fwui-web
    restart: unless-stopped
    depends_on:
      - fwui
    volumes:
      - static_volume:/var/www/html/static:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Europe/Paris
    ports:
      - 80:80

volumes:
  static_volume:
  database_volume:
