version: "3.7"
services:
  fwui:
    build:
      context: ..
      dockerfile: ./Dockerfile    
    restart: unless-stopped
    privileged: true
    volumes:
      - static_volume:/app/static
      - database_volume:/app/database
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /var/run/dbus:/var/run/dbus
      - /var/log/journal:/var/log/journal:ro            
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SALT=0123456789
      - SECRET_KEY=01234567890123456789

  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - fwui
    volumes:
      - static_volume:/var/www/html/static:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
    ports:
      - 80:80

volumes:
  static_volume:
  database_volume:
